version: '3'
services:
  web:
    build: .
    ports:
      - 80:80
    depends_on:
      - db
    volumes: 
     - .:/teste
    command: ["rails", "s", "-b", "0.0.0.0" , "-p" , "80"]
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - Mochila:/var/lib/mysql

volumes:
  Mochila:

networks:
  default:
    external:
      name: ponte
