version: '3'
services:
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes: 
     - .:/teste
    command: ["rails", "s", "-b", "0.0.0.0"]
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
       