development:
  adapter: mysql2
  database: esperto_fit_academy_development
  username: root
  password: example
  host: db
  port: 3306

test:
  adapter: mysql2
  database: esperto_fit_academy_test
  username: root
  password: example
  host: db
  port: 3306
